.class public Lcom/powervision/natives/PowerCamCallBack;
.super Ljava/lang/Object;
.source "PowerCamCallBack.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGetMuxerFormatListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnSetMuxerFormatListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnSetGestureOnlyDiscerningTypeListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGetGestureFirstTimeTeachingStateListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnSetGestureFirstTimeTeachingStateListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnSDStorageSlowListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGetTypeCModeListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnSetTypeCModeListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnCameraSingleEngineArmExceptionListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnCameraSDCardSpeedDetectedListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnCameraSensorHighTemperatureListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnCameraStopRecordStateListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGestureInternalStorageFullListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGestureSDFullListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGetAudioRateListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnSetAudioRateListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnPhotoStateListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGetHeadLightStateListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnEnableHeadLightListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnRecordDurationListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnIsSaveLapsePhotoListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnOnHDRMultiplePhotoStateListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnOnAEBMultiplePhotoStateListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnMultiplePhotoListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGetGestureStat;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnEnableGesture;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnStopLapsePhoto;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnCreateLapseFiile;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGetLapseSnap;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGetLapseFileDuration;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnLapsePhotoNumber;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnLapseFileDuration;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnDelayPhoto;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGestureStopTrack;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGestureStartTrack;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGestureStopRecord;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGestureStartRecord;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGestureSnapGroup;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGestureSnap;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnForwardLamp;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnSetRtspBitrateListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGetRtspBitrateListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnEnableLogoListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGetLuminanceListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGetContrastListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGetSaturationListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnGetPhotoStyleListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnConnectAudioListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnSetSysTimeListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnEnableAudioListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnInternalStorageFullListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyOnSDFullListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyHistogramDataListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyGetCameraAllParametersListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyStopDelayTimePhotoListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetPhotoFileFormatListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyGetPhotoFileFormatListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyGetRestRecordTimeListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyGetEmmcStorageSizeListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyGetSDStorageSizeListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyGetRecordTimeListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyGetRestPhotoNumberListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyFormatStorageDeviceListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetCurrentStorageDeviceListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyGetStorageDeviceTypeListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetCaptureModeListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyResetCameraParamListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyEnableResistBlinkListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyEnableHistogramListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetSaturationListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetContrastListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetLuminanceListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetPhotoStyleListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetWhiteBalanceListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyGetWhiteBalanceListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetMeteringModeListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetEVListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetExposureTimeListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetISOListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetExposureModeListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyGetCurrentExposureStatusListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyStatusConnectionListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyGetVisionVersion;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyGetCurrentResolutionListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyGetCameraVersionListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyGetCameraWorkStateListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySwitchToSnapModeListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySwitchToRecordModeListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyGetSDStateListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyEnableHDRListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyStopRecordListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyStartRecordListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyStartPhotoListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetPhotoResolutionListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetVideoResolutionListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetLongTimeExposureListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyChangeRtspBitRateListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifySetShutterSpeedListener;,
        Lcom/powervision/natives/PowerCamCallBack$CameraNotifyConnectionListener;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 3
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
